# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x61\x63\x65_detection.proto\x12\x0e\x66\x61\x63\x65_detection\"\"\n\x12\x44\x65tectFacesRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"v\n\x07\x45motion\x12\r\n\x05\x61ngry\x18\x01 \x01(\x02\x12\x0f\n\x07\x64isgust\x18\x02 \x01(\x02\x12\x0c\n\x04\x66\x65\x61r\x18\x03 \x01(\x02\x12\r\n\x05happy\x18\x04 \x01(\x02\x12\x0b\n\x03sad\x18\x05 \x01(\x02\x12\x10\n\x08surprise\x18\x06 \x01(\x02\x12\x0f\n\x07neutral\x18\x07 \x01(\x02\"Y\n\x06Region\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01w\x18\x03 \x01(\x02\x12\t\n\x01h\x18\x04 \x01(\x02\x12\x10\n\x08left_eye\x18\x05 \x03(\x02\x12\x11\n\tright_eye\x18\x06 \x03(\x02\"$\n\x06Gender\x12\r\n\x05Woman\x18\x01 \x01(\x02\x12\x0b\n\x03Man\x18\x02 \x01(\x02\"d\n\x04Race\x12.\n\x05races\x18\x01 \x03(\x0b\x32\x1f.face_detection.Race.RacesEntry\x1a,\n\nRacesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xa3\x02\n\x13\x44\x65tectFacesResponse\x12(\n\x07\x65motion\x18\x01 \x01(\x0b\x32\x17.face_detection.Emotion\x12\x18\n\x10\x64ominant_emotion\x18\x02 \x01(\t\x12&\n\x06region\x18\x03 \x01(\x0b\x32\x16.face_detection.Region\x12\x17\n\x0f\x66\x61\x63\x65_confidence\x18\x04 \x01(\x02\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x02\x12&\n\x06gender\x18\x06 \x01(\x0b\x32\x16.face_detection.Gender\x12\x17\n\x0f\x64ominant_gender\x18\x07 \x01(\t\x12\"\n\x04race\x18\x08 \x01(\x0b\x32\x14.face_detection.Race\x12\x15\n\rdominant_race\x18\t \x01(\t\"R\n\x18\x44\x65tectFacesResponseArray\x12\x36\n\tresponses\x18\x01 \x03(\x0b\x32#.face_detection.DetectFacesResponse2s\n\x14\x46\x61\x63\x65\x44\x65tectionService\x12[\n\x0b\x44\x65tectFaces\x12\".face_detection.DetectFacesRequest\x1a(.face_detection.DetectFacesResponseArrayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RACE_RACESENTRY']._options = None
  _globals['_RACE_RACESENTRY']._serialized_options = b'8\001'
  _globals['_DETECTFACESREQUEST']._serialized_start=40
  _globals['_DETECTFACESREQUEST']._serialized_end=74
  _globals['_EMOTION']._serialized_start=76
  _globals['_EMOTION']._serialized_end=194
  _globals['_REGION']._serialized_start=196
  _globals['_REGION']._serialized_end=285
  _globals['_GENDER']._serialized_start=287
  _globals['_GENDER']._serialized_end=323
  _globals['_RACE']._serialized_start=325
  _globals['_RACE']._serialized_end=425
  _globals['_RACE_RACESENTRY']._serialized_start=381
  _globals['_RACE_RACESENTRY']._serialized_end=425
  _globals['_DETECTFACESRESPONSE']._serialized_start=428
  _globals['_DETECTFACESRESPONSE']._serialized_end=719
  _globals['_DETECTFACESRESPONSEARRAY']._serialized_start=721
  _globals['_DETECTFACESRESPONSEARRAY']._serialized_end=803
  _globals['_FACEDETECTIONSERVICE']._serialized_start=805
  _globals['_FACEDETECTIONSERVICE']._serialized_end=920
# @@protoc_insertion_point(module_scope)
