# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import face_detection_pb2 as face__detection__pb2


class FaceDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectFaces = channel.unary_unary(
                '/face_detection.FaceDetectionService/DetectFaces',
                request_serializer=face__detection__pb2.DetectFacesRequest.SerializeToString,
                response_deserializer=face__detection__pb2.DetectFacesResponseArray.FromString,
                )


class FaceDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectFaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFaces,
                    request_deserializer=face__detection__pb2.DetectFacesRequest.FromString,
                    response_serializer=face__detection__pb2.DetectFacesResponseArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face_detection.FaceDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face_detection.FaceDetectionService/DetectFaces',
            face__detection__pb2.DetectFacesRequest.SerializeToString,
            face__detection__pb2.DetectFacesResponseArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
